### ISSUE TITLE
the process consumes too much resources

### ISSUE THREAD

**Issue by IiroUllin** [efoerster/evince-synctex#1]
The evince-synctex process pretty much loads one of the CPU cores to its max while evince window with a forward search is open. This consumes lots of power and limits utility of this great script in mobile settings.

**Comment by IiroUllin** [comment]
I tested the script and found that the issue is caused by the GLib.idle_add(...) in line 180 which causes the termination check be constantly called. Replaced it with

GLib.timeout_add(1000,poll_viewer_process) 

after which the problem is no more!

**Comment by dr-br** [comment]
Would it be envisageable to replace line 180 accordingly? evince-synctex.py is used by the zed-latex extension, the high cpu load is annoying.
